-- MySQL Script generated by MySQL Workbench
-- Thu Jan 20 22:18:16 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema paymybuddy
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`bankAccount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bankAccount` (
  `idBankaccount` INT NOT NULL AUTO_INCREMENT,
  `iban` INT NOT NULL,
  `bic` VARCHAR(45) NOT NULL,
  `accountnumber` VARCHAR(45) NOT NULL,
  `amount` DOUBLE NOT NULL,
  PRIMARY KEY (`idBankaccount`),
  UNIQUE INDEX `idBankAccount_UNIQUE` (`idBankaccount` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `account` DOUBLE NULL,
  `idBankaccount` INT NOT NULL,
  PRIMARY KEY (`idUser`),
  INDEX `fk_user_bankAccount1_idx` (`idBankaccount` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC),
  CONSTRAINT `fk_user_bankAccount1`
    FOREIGN KEY (`idBankaccount`)
    REFERENCES `mydb`.`bankAccount` (`idBankaccount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`transaction` (
  `idTransaction` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NOT NULL,
  `amount` DOUBLE NOT NULL,
  `idEmitter` INT NOT NULL,
  `idReceiver` INT NOT NULL,
  PRIMARY KEY (`idTransaction`),
  INDEX `fk_transaction_user1_idx` (`idEmitter` ASC),
  INDEX `fk_transaction_user2_idx` (`idReceiver` ASC),
  UNIQUE INDEX `idTransaction_UNIQUE` (`idTransaction` ASC),
  CONSTRAINT `fk_transaction_user1`
    FOREIGN KEY (`idEmitter`)
    REFERENCES `mydb`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transaction_user2`
    FOREIGN KEY (`idReceiver`)
    REFERENCES `mydb`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`enterprise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`enterprise` (
  `idEnterprise` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(55) NOT NULL,
  `idBankAccount` INT NOT NULL,
  `siret` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEnterprise`),
  INDEX `fk_entreprise_bankAccount1_idx` (`idBankAccount` ASC),
  UNIQUE INDEX `idEnterprise_UNIQUE` (`idEnterprise` ASC),
  CONSTRAINT `fk_entreprise_bankAccount1`
    FOREIGN KEY (`idBankAccount`)
    REFERENCES `mydb`.`bankAccount` (`idBankaccount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_has_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_has_user` (
  `idUser` INT NOT NULL,
  `idFriend` INT NOT NULL,
  PRIMARY KEY (`idUser`, `idFriend`),
  INDEX `fk_user_has_user_user1_idx` (`idFriend` ASC),
  INDEX `fk_user_has_user_user_idx` (`idUser` ASC),
  CONSTRAINT `fk_user_has_user_user`
    FOREIGN KEY (`idUser`)
    REFERENCES `mydb`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_user_user1`
    FOREIGN KEY (`idFriend`)
    REFERENCES `mydb`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`commission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`commission` (
  `idCommission` INT NOT NULL AUTO_INCREMENT,
  `pourcentage` DOUBLE NOT NULL,
  `idUser` INT NOT NULL,
  `idEnterprise` INT NOT NULL,
  `idTransaction` INT NOT NULL,
  PRIMARY KEY (`idCommission`),
  INDEX `fk_commission_user1_idx` (`idUser` ASC),
  INDEX `fk_commission_entreprise1_idx` (`idEnterprise` ASC),
  INDEX `fk_commission_transaction1_idx` (`idTransaction` ASC),
  UNIQUE INDEX `idCommission_UNIQUE` (`idCommission` ASC),
  CONSTRAINT `fk_commission_user1`
    FOREIGN KEY (`idUser`)
    REFERENCES `mydb`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commission_entreprise1`
    FOREIGN KEY (`idEnterprise`)
    REFERENCES `mydb`.`enterprise` (`idEnterprise`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commission_transaction1`
    FOREIGN KEY (`idTransaction`)
    REFERENCES `mydb`.`transaction` (`idTransaction`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
